### ISSUE TITLE
Rive File keeps blinking by useing Rive Render some devices.

### ISSUE THREAD

**Issue by blueparkyanadoocorp** [rive-app/rive-android#361]
<-- Thanks for using Rive!

If something isn't working like you expected, please:

- Make sure you've updated rive-android to the latest version: Yes, 10.0.3
     
### Description

There has a problem by using rive renderer.
Rive file keeps blinking like under the video.
But this is happening on few devices, not all devices.

### Provide a Repro

[ComposeActivity.kt.zip](https://github.com/user-attachments/files/19545165/ComposeActivity.kt.zip)

### Expected behavior

Not blinking Rive File.

#### Video

[rive_blinking.mp4.zip](https://github.com/user-attachments/files/19545182/rive_blinking.mp4.zip)

### Device & Versions (please complete the following information)

UnNormal Behavior Devices - Galaxy Note 10 / OS 12, Galaxy S10+ / OS 12

**Comment by Matthew-R-Rohr** [comment]
We have noticed the same blinking issue, happening more on Pixel devices.  We have since had to revert to the Skia renderer.

**Comment by blueparkyanadoocorp** [comment]
Hello Again.

Rive Developer was helped this issue.
So I checked that unnormal behavior devices(Galaxy Note 10 / OS 12, Galaxy S10+ / OS 12) to be normal in version 10.0.5.

So I released my application and this bug is come again.
I have to downgrade version 10.0.5 > 9.13.5 again.

Recently Unnormal Behavior Device is SM-S721N.

Please check this bug again.
Thank you.

@rive-engineering

**Comment by sherbaev** [comment]
I am also facing the same issue tried 10.0.5 and 10.1.0 and issue is reproducible on both versions. Device is android 8.0 samsung galaxy s8

**Comment by blueparkyanadoocorp** [comment]
I realized that SM-S721N / OS 14 is keep happened in version 9.13.5.
So I downgrade version 9.13.5 > 9.10.1.
Then this bug is solved.

So version 9.13.5 is already happended kind of this bug.

@rive-engineering

**Comment by csmartdalton** [comment]
@blueparkyanadoocorp are you saying that you enabled the Rive renderer on 9.13.5 and saw this issue? But on 9.10.1 with the Rive renderer also, the issue is not there?

**Comment by csmartdalton** [comment]
@blueparkyanadoocorp we have been compiling and running your ComposeActivity.kt sample on various devices, including Galaxy S8, Galaxy S9, and Galaxy A8, but no luck yet with a repro. Are you able to share a fully compilable Android project that shows the repro? I would LOVE to fix this but still just can't get a repro!

**Comment by csmartdalton** [comment]
Ok, great news! I managed to get a repro on Galaxy A8, from before 10.0.5:

https://github.com/user-attachments/assets/e036e206-5bb2-454b-8c42-7299fdf49f4c

I've also verified that this specific issue was fixed with https://github.com/rive-app/rive-runtime/commit/8d856edaf4ba8ec51b11f2b754987b1eb8fc54eb, which landed in 10.0.5:

https://github.com/user-attachments/assets/c3bda749-840f-4e35-8179-593ab65a6df1

@blueparkyanadoocorp can you describe the issue you're seeing after 10.0.5? Is it the same or something different?

**Comment by blueparkyanadoocorp** [comment]
@csmartdalton 
Hello I mistaken that version 9.13.5 is problem with Skia Renderer.
But I used version 9.13.5 with Rive Renderer.

So To summarize by SM-S721N / OS 14

rive version 9.13.5 + Skia Renderer -> O
rive version 9.13.5 + Rive Renderer -> X(has blinking issue)
rive version 10.1.4 + Rive Renderer -> X(has blinking issue)

Recently Rive version still has same issue.

Thank you.

**Comment by HayesGordon** [comment]
Hi @blueparkyanadoocorp I've also confirmed that the issue appears to be resolved using the latest version of the runtime. Tested on a Galaxy S24 SM-921B/DS, which has an Exynos CPU, which is what had the issue.

Before the fix:

https://github.com/user-attachments/assets/1741fdd9-47d3-487c-b633-5f01f46e3190

After the fix:

https://github.com/user-attachments/assets/8ab4f854-bed6-4cdc-ab38-0bcd681b4774

On our side, we're not able to reproduce this issue anymore. If you're still encountering it can you please provide a full sample project reproducing the issue (maybe it's contingent on other factors).

**Comment by blueparkyanadoocorp** [comment]
@HayesGordon Hi, I try to upload android sample made in zip. but this is too big so I can't upload it.
So I upload sample project in my repository. ([upload](https://github.com/blueparkyanadoocorp/rive-android-test))
But please note that is same with rive android sample.

And Please refer to the photos and video below. Thank you.

https://github.com/user-attachments/assets/86a8f477-fb69-425e-ab8b-53cac175b14b

https://github.com/user-attachments/assets/15b757d8-c36b-4b55-92c2-2c088d97a737

**Comment by lemixd** [comment]
I'm having the same issue with the Rive renderer on the Samsung S24+ SM-S926B/DS (Exynos edition) after upgrading to Android 15. There were noticeable FPS drops on Android 14, but now all Rive animations are completely broken (10.1.4, native android runtime).

I've noticed, that the issue persists even when viewing animations with rive renderer on the web (same device).

https://github.com/user-attachments/assets/b24997a1-9ec2-43f5-a0db-4e8efab6bd85

**Comment by sarthak-cars24** [comment]
Update on the issue, seems like its breaking on Samsung phones running Android 15 on Exynos. @blueparkyanadoocorp Can you confirm if you are facing any other issues on 9.10.1?

**Comment by sarthak-cars24** [comment]
Hey, guys any update on the issue. This seems to be happening on **Rive Renderer and mostly noticed on Samsung's Exynos based devices**. Its rapidly becoming a problem for adoption. Would love to resolve this somehow as switching to **Skia** is triggering app size concerns.

**Comment by Tod-Rive** [comment]
The latest version ([10.2.1](https://github.com/rive-app/rive-android/releases/tag/10.2.1)) of the Android runtime has a [fix](https://github.com/rive-app/rive-android/commit/1df3665aed23f122cbe7bd5963680a3dc7dd4692) specifically for Exynos device issues. Please try it and let us know if you still have issues.

**Comment by kancic** [comment]
> The latest version ([10.2.1](https://github.com/rive-app/rive-android/releases/tag/10.2.1)) of the Android runtime has a [fix](https://github.com/rive-app/rive-android/commit/1df3665aed23f122cbe7bd5963680a3dc7dd4692) specifically for Exynos device issues. Please try it and let us know if you still have issues.

The latest 10.2.1 version has fixed my issues on S24 android 15 but now the app crashes like mentioned. 

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffffff in tid 12286 (Profile Saver), pid 12270

**Comment by HayesGordon** [comment]
We recently released https://github.com/rive-app/rive-android/releases/tag/10.3.1 which addresses an issue that was introduced in later versions, and likely the cause of the above mentioned crash.

I'm marking this issue as resolved (the rendering bug).

If you're experiencing other issues on the latest version, please open a new issue for us to track.
